vpc:
  name: "staging-VPC"
  cidr-block: "10.2.0.0/16"

subnets:
  pub_subnet: "10.2.1.0/24"
  pub_subent: "10.2.2.0/24"
  pub_subnet: "10.2.3.0/24"
  pvt_subnet: "10.2.4.0/24"
  pvt_subnet: "10.2.5.0/24"
  pvt_subnet: "10.2.6.0/24"