vpc:
  name: "prod-VPC"
  cidr-block: "10.3.0.0/16"

subnets:
  pub_subnet: "10.3.1.0/24"
  pub_subnet: "10.3.2.0/24"
  pub_subnet: "10.3.3.0/24"
  pvt_subnet: "10.3.4.0/24"
  pvt_subnet: "10.3.5.0/24"
  pvt_subnet: "10.3.6.0/24"